#ifndef UNIVERSAL_WRITE_RENDERING_LAYERS_PRAGMAS_INCLUDED
#define UNIVERSAL_WRITE_RENDERING_LAYERS_PRAGMAS_INCLUDED

/* SLZ MODIFIED - We don't use rendering layers!
#pragma multi_compile_fragment _ _WRITE_RENDERING_LAYERS
#pragma target 4.5 _WRITE_RENDERING_LAYERS
*/

#endif // UNIVERSAL_WRITE_RENDERING_LAYERS_PRAGMAS_INCLUDED
