#ifndef SLZ_DXC_STATE
	#define SLZ_DXC_STATE
	#define SLZ_DXC_UPDATED
	#define SLZ_DXC_VERSION_MAJOR 1
	#define SLZ_DXC_VERSION_MINOR 7
	#define SLZ_DXC_VERSION_PATCH 2308
	#define SLZ_DXC_VERSION_BUILD 82
#endif